version: '3'

services:
  app:
    build: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s java -jar schoolie-image.jar
    networks:
      - "schoolie-network"
    tty: true
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/schoolie
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=schoolie
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - "schoolie-network"
networks:
  schoolie-network:
    driver: bridge